imports:
    - { resource: "default.yml" }
    - { resource: "routing.yml", property: "routing.a.b.c" }

a: first
z: "%configuration_directory_path%"

parameters:
    port: 8080
    controllers_path: "%z%/../controllers"
