services:
    example_configuration:
        class: "Command/ConfigurationCommand"
        arguments:
            - "%parameters.foo%"
            - "%parameters.port%"
            - "%routing%"
            - "@solfege_configuration"
            - "@example_toc"
        calls:
            - [addSomething, ["@solfege_configuration", "%parameters.foo%"]]
        tags:
            - { name: "solfege.console.command" }


    example_class:
        class: "Klass/Toc"

    example_toc:
        class: "@example_class"
