services:
    example_configuration:
        class: "Command/ConfigurationCommand"
        arguments:
            - "%parameters.foo%"
            - "%parameters.port%"
            - "%routing%"
            - "@solfege_configuration"
        tags:
            - { name: "solfege.console.command" }
